#define ID_RESOURCE 100
#define ID_DRAGBMP  120
#define IDB_ATWORK  125
#define IDM_FILE    130
#define IDM_EXIT    140
#define IDM_NEW     150
#define IDM_VIEW    151
#define IDM_SMALL   152
#define IDM_MEDIUM  154
#define IDM_LARGE   156
#define IDM_CDROM   157
#define IDM_DETAIL  160
#define IDM_SORTMENU 165
#define IDM_SORTSIZE 166
#define IDM_SORTNAME 167
#define IDM_SLIDESHOW 168

#define IDM_SEL     200
#define IDM_NONE    202
#define IDM_EDIT    205
#define IDM_RELOAD  208
#define IDM_HELPMENU 220
#define IDM_HELP     222
#define IDM_HELPINDEX 223
#define IDM_ABOUT    224

/*
** pogress dialog
*/
#define DLG_PROGRESS    250
#define TXT_FILENAME    252
#define CTRL_SLIDER     254
#define ID_PROGRESSWND 260
/*
** TREE CONTROL DEFINES
*/
#define ID_FOLDER_ICON  401
#define ID_NETDRV_ICON  402
#define ID_HRDDRV_ICON  403
#define ID_FLPDRV_ICON  404
#define ID_CDDRV_ICON   405

#define DLG_TREECOPYPROGRESS 450
#define ID_TREEPROGRESSWND   455

/*
** String resources
*/
#define IDS_DELETEIMG  1000
#define IDS_DOSCOPYERR 1002
#define IDS_SELECTED   1003
#define IDS_FILE_NOT_FOUND                 1010
#define IDS_PATH_NOT_FOUND                 1011
#define IDS_ACCESS_DENIED                  1012
#define IDS_NOT_DOS_DISK                   1013
#define IDS_SHARING_VIOLATION              1014
#define IDS_SHARING_BUFFER_EXCEEDED        1015
#define IDS_INVALID_PARAMETER              1016
#define IDS_FILENAME_EXCED_RANGE           1017
#define IDS_REPLACE_FILE                   1020
#define IDS_WARNING                        1022
#define IDS_DELQUESTION                    1024
#define IDS_CANNOTDELETE                   1026
#define IDS_FOLDERSTRING                   1028
#define IDS_DETAILSTRING                   1030
#define IDS_WRITE_PROTECT                  1032
/*
** tbar
*/
#define IDB_SELECT  1400
#define IDB_ROTLEFT 1402
#define IDB_ROTRIGHT 1403
#define IDB_ZOOM    1405
#define IDB_DELETE  1410
#define IDB_SMALL   1420
#define IDB_MEDIUM  1425
#define IDB_LARGE   1430
#define IDB_SORTSIZE 1435
#define IDB_SORTNAME 1440
#define IDB_PROJECT  1445
#define IDB_TBAR     1450
/*
** help
*/
#define IDS_HELPLIBRARYNAME         1500
#define IDS_CANNOTLOADSTRING        1505
#define IDS_HELPLOADERROR           1510
#define IDS_HELPDISPLAYERROR        1515
#define IDS_HELPWINDOWTITLE         1520
#define IDS_HELPGENERALERROR        1525
#define IDS_HELPKEYSERROR           1530
#define IDS_HELPINDEXERROR          1535
